from .roles import RoleDefinition, RoleSpecialAbility

ROLES: dict[str, RoleDefinition] = {
    "sherpa": RoleDefinition(
        id="sherpa",
        display_name="Sherpa",
        difficulty="Easy",
        hp_delta=5,
        stamina_delta=15,
        willpower_delta=-5,
        stamina_cost_multiplier=0.85,
        starting_equipment={"rope_sections": 2},
        special_ability=RoleSpecialAbility.SHERPA_FALL_RESISTANCE,
        ability_params={"fall_chance_multiplier": 0.7},
        description="Guía de montaña experimentado. Más eficiente físicamente, pero con menor fuerza de voluntad.",
    ),
    "clasico": RoleDefinition(
        id="clasico",
        display_name="Alpinista Clásico",
        difficulty="Hard",
        hp_delta=5,
        stamina_delta=5,
        willpower_delta=5,
        stamina_cost_multiplier=1.10,
        special_ability=RoleSpecialAbility.NONE,
        ability_params={},
        description="El purista. Buenos stats en todo, pero sin red de seguridad ni habilidad especial.",
    ),
    "investigador": RoleDefinition(
        id="investigador",
        display_name="Investigador",
        difficulty="Medium",
        hp_delta=-10,
        stamina_delta=-15,
        willpower_delta=20,
        stamina_cost_multiplier=1.05,
        starting_equipment={"oxygen_pct": 10},
        special_ability=RoleSpecialAbility.INVESTIGATOR_FORECAST,
        ability_params={"forecast_reliability_bonus": 0.25},
        description="Científico de altura. Entiende el clima, pero tu cuerpo no está tan preparado.",
    ),
    "tecnico": RoleDefinition(
        id="tecnico",
        display_name="Escalador Técnico",
        difficulty="Normal",
        hp_delta=0,
        stamina_delta=0,
        willpower_delta=0,
        stamina_cost_multiplier=0.95,
        starting_equipment={"rope_sections": 2, "gas_canisters": 1},
        special_ability=RoleSpecialAbility.TECNICO_ALTITUDE_DISCOUNT,
        ability_params={"altitude_threshold": 7000, "stamina_discount": 0.90},
        description="Especialista en terreno vertical. Equipado para lo técnico, más eficiente en altura.",
    ),
    "medico": RoleDefinition(
        id="medico",
        display_name="Médico de Expedición",
        difficulty="Medium",
        hp_delta=-5,
        stamina_delta=-10,
        willpower_delta=15,
        stamina_cost_multiplier=1.0,
        starting_equipment={"food_rations": 2, "oxygen_pct": 10},
        special_ability=RoleSpecialAbility.MEDICO_FREE_HEAL,
        ability_params={"free_heal_amount": 15, "hp_event_mitigation": 0.20},
        description="Doctor de montaña. Sabe mantenerse vivo cuando el cuerpo falla.",
    ),
}
