from typing import Protocol

from app.models.game_state import GameState


class AbstractSessionRepository(Protocol):
    def get(self, session_id: str) -> GameState | None: ...

    def save(self, state: GameState) -> None: ...

    def delete(self, session_id: str) -> None: ...

    def list_all(self) -> list[GameState]: ...

    def cleanup_expired(self) -> int: ...